import { db } from "@/db/client";
import { diaryEntries } from "@/db/schema";
import { regenerateDailyEntry } from "@/modules/journal/generator";

const TERSE_WORD_THRESHOLD = 150;

/**
 * Scans for journal entries that need regeneration:
 * 1. Entries generated by non-Claude fallback models
 * 2. Terse entries (< 150 words) regardless of model
 * Attempts to regenerate them with Claude (noFallback).
 * Skips entries without generationMetadata (pre-tracking, assumed Claude).
 */
export async function regenerateFallbackEntries(): Promise<void> {
  console.log("[regenerate-fallback] Scanning for low-quality entries...");

  const allEntries = await db
    .select({
      date: diaryEntries.date,
      content: diaryEntries.content,
      generationMetadata: diaryEntries.generationMetadata,
    })
    .from(diaryEntries);

  const candidates = allEntries.filter((entry) => {
    const meta = entry.generationMetadata as Record<string, unknown> | null;
    if (meta?.regenerated === true) return false;

    // Candidate 1: non-Claude model
    if (meta?.model) {
      const model = String(meta.model);
      if (!model.startsWith("claude")) return true;
    }

    // Candidate 2: terse entry (< 150 words) regardless of model
    const wordCount = entry.content.split(/\s+/).filter(Boolean).length;
    if (wordCount < TERSE_WORD_THRESHOLD) return true;

    return false;
  });

  if (candidates.length === 0) {
    console.log("[regenerate-fallback] No low-quality entries found. All good.");
    return;
  }

  console.log(`[regenerate-fallback] Found ${candidates.length} entries to regenerate.`);

  let succeeded = 0;
  let failed = 0;
  const failedDates: string[] = [];

  for (const entry of candidates) {
    const wordCount = entry.content.split(/\s+/).filter(Boolean).length;
    const meta = entry.generationMetadata as Record<string, unknown> | null;
    const model = meta?.model ? String(meta.model) : "unknown";
    const reason = !model.startsWith("claude") ? `fallback model (${model})` : `terse (${wordCount} words)`;

    try {
      const result = await regenerateDailyEntry(entry.date);
      console.log(
        `[regenerate-fallback] Regenerated ${entry.date} (${reason}) with ${result.modelUsed}`
      );
      succeeded++;
    } catch (err) {
      console.error(
        `[regenerate-fallback] Failed to regenerate ${entry.date} (${reason}):`,
        err instanceof Error ? err.message : err
      );
      failed++;
      failedDates.push(entry.date);
    }
  }

  console.log(
    `[regenerate-fallback] Done. Regenerated: ${succeeded}, Failed: ${failed}` +
    (failedDates.length > 0 ? `, Failed dates: ${failedDates.join(", ")}` : "")
  );
}
