import { db } from "@/db/client";
import { diaryEntries } from "@/db/schema";
import { regenerateDailyEntry } from "@/modules/journal/generator";
import { isNotNull } from "drizzle-orm";

/**
 * Scans for journal entries generated by non-Claude fallback models
 * and attempts to regenerate them with Claude (noFallback).
 * Skips entries without generationMetadata (pre-tracking, assumed Claude).
 */
export async function regenerateFallbackEntries(): Promise<void> {
  console.log("[regenerate-fallback] Scanning for fallback-generated entries...");

  const fallbackEntries = await db
    .select({ date: diaryEntries.date, generationMetadata: diaryEntries.generationMetadata })
    .from(diaryEntries)
    .where(
      isNotNull(diaryEntries.generationMetadata)
    );

  // Filter to entries where model is not Claude and not already regenerated
  const candidates = fallbackEntries.filter((entry) => {
    const meta = entry.generationMetadata as Record<string, unknown> | null;
    if (!meta?.model) return false;
    const model = String(meta.model);
    if (model.startsWith("claude")) return false;
    if (meta.regenerated === true) return false;
    return true;
  });

  if (candidates.length === 0) {
    console.log("[regenerate-fallback] No fallback entries found. All good.");
    return;
  }

  console.log(`[regenerate-fallback] Found ${candidates.length} fallback entries to regenerate.`);

  let succeeded = 0;
  let failed = 0;

  for (const entry of candidates) {
    try {
      const result = await regenerateDailyEntry(entry.date);
      console.log(
        `[regenerate-fallback] Regenerated ${entry.date} with ${result.modelUsed}`
      );
      succeeded++;
    } catch (err) {
      console.error(
        `[regenerate-fallback] Failed to regenerate ${entry.date}:`,
        err instanceof Error ? err.message : err
      );
      failed++;
      // Stop trying more entries if Claude is down — no point burning through them
      break;
    }
  }

  console.log(
    `[regenerate-fallback] Done. Regenerated: ${succeeded}, Failed: ${failed}, Remaining: ${candidates.length - succeeded - failed}`
  );
}
